name: Build Crowdin Translation Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-crowdin-translation-packages:
    runs-on: ubuntu-24.04

    steps:
      - name: Orchard CMS
        uses: andrii-bodnar/crowdin-request-action@ee7a2af9564d8934b5b4a8427185aaaffee0165e # v0.3.0
        with:
          route: POST /projects/{projectId}/translations/builds
          projectId: 46524
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}

      - name: Orchard CMS Gallery
        uses: andrii-bodnar/crowdin-request-action@ee7a2af9564d8934b5b4a8427185aaaffee0165e # v0.3.0
        with:
          route: POST /projects/{projectId}/translations/builds
          projectId: 63766
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
