name: Compile

on:
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    defaults:
      run:
        shell: cmd
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.1.0

      - name: Restore NuGet packages
        run: nuget restore src/Orchard.sln

      - name: Compile
        run: msbuild Orchard.proj /m /t:Compile /p:MvcBuildViews=true /p:TreatWarningsAsErrors=true
