name: SpecFlow tests
# Compiles the solution and runs unit tests, as well the SpecFlow tests on the main development branches.

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight.

jobs:
  compile:
    name: SpecFlow tests
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    strategy:
      matrix:
        branch: [dev, 1.10.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ matrix.branch }}

      - name: Restore NuGet packages
        run: nuget restore src/Orchard.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Compile
        run: msbuild Orchard.proj /m /t:Compile /p:MvcBuildViews=true /p:TreatWarningsAsErrors=true -WarnAsError

      - name: Test
        run: msbuild Orchard.proj /m /t:Test

      - name: Spec
        run: msbuild Orchard.proj /m /t:Spec
